
version: '3.3'
services:
  PaymentDB:
    hostname: postgres-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '9999:5432'
    volumes:
      - my-db:/var/lib/postgresql

volumes:
  my-db:
